services:
  # Python Flask ML API
  - type: web
    name: mental-health-ml-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT api:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: FLASK_ENV
        value: production

  # Node.js Backend
  - type: web
    name: mental-health-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

  # React Frontend
  - type: web
    name: mental-health-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    rootDir: .